---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseMethodName:
        enabled: true
        exclude_paths:
        - src/Jade/Stream/Template.php
      UnusedFormalParameter:
        enabled: true
        exclude_paths:
        - src/Jade/Stream/Template.php
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
